#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# 参考编译流程 https://github.com/firkerword/openwrt-Exclusive
# 参考编译流程 https://github.com/esirplayground/AutoBuild-OpenWrt
#=================================================

name: Hinlink H68K

on: 
  workflow_dispatch:
  schedule:
     - cron: 0 22 * * 5
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 检查项目分支
      uses: actions/checkout@main

    - name: 清理磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
        
    - name: 安装编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        df -hT
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://github.com/firkerword/openwrt-list/raw/master/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        
    - name: 下载固件源码
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "src-git ssrp https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
        
    - name: 下载插件
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a   
        
    # - name: 自定义插件设置
    #  working-directory: ./openwrt
    #  run: |
    #    rm -rf feeds/packages/net/v2ray-geodata
    #    git clone https://github.com/NEARWN/v2ray-geodata feeds/packages/net/v2ray-geodata
    #    git clone "your_github_link" package/"your_folder_name"              
    
    - name: 加载配置文件
      env:
        CONFIG_FILE: 'config/h68k.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt && make defconfig
        
    - name: 下载安装包
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: 开始编译固件
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        
    - name: 查看磁盘使用情况
      if: (!cancelled())
      run: df -hT
        
    - name : 上传固件到github
      uses: actions/upload-artifact@master
      with:
        name:  Hinlink H68K
        path: openwrt/bin
